### PR TITLE
Reset default EntrypointLookup on exception to fix #21 and #73

### LINKED ISSUE #910: Tricky error related to 500 error pages
Yesterday I merged #909 as an (ugly) temporary solution to a very tricky error.

How to reproduce the error:

* Use `prod` and `debug=0` in `.env`
* Comment the `DATABASE_URL` config to trigger a 500 error
* The 500 error page sometimes is styled with CSS and sometimes isn't:
  * The 500 error for this page shows styles: `/en/blog/posts/lorem-ipsum-dolor-sit-amet-consectetur-adipiscing-elit`
  * The 500 error for this page doesn't: `/en/blog/`

Can anyone spot the reason and provide a pull request to fix it? Thanks!

### PR DESCRIPTION
**Pull request by tbmatuka**
Since @ckrack seems to be unavailable to continue working on #21, I figured this would be faster :)

I don't like having `_default` hardcoded in the listener, but I see no other options right now.
I thought about adding a `resetAll()` method to EntrypointLookupCollection, but there were a couple of issues with that:
1. It would either be a BC break if I added it to the interface, or an important method that isn't interfaced and I don't really like either of those.
2. I couldn't even implement it because the container that we get in the collection only has `has()` and `get()` methods, so I couldn't go through it. This would also have to be replaced (and break BC) to implement `resetAll()`.

Fixes https://github.com/symfony/demo/issues/910

### CODE REVIEW

**Comment by Lyrkan** [comment]
> I don't like having _default hardcoded in the listener, but I see no other options right now.
> I thought about adding a resetAll() method to EntrypointLookupCollection, but there were a couple of issues with that

Wouldn't it be possible to handle that using the `WebpackEncoreExtension` (even though I agree that having a `all()` and/or a `resetAll()` in the `EntrypointLookupCollection` would have been a better solution)?

1) add a `$builds` argument to the constructor of `webpack_encore.exception_listener`
2) use `$container->getDefinition('webpack_encore.exception_listener')->replaceArgument(...)` to inject the list of available builds in it

**Comment by tbmatuka** [comment]
I made it work like you suggested. I still don't love it, but I like it a lot better than before.

File: src/EventListener/ExceptionListener.php [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+namespace Symfony\WebpackEncoreBundle\EventListener;
+
+use Symfony\WebpackEncoreBundle\Asset\EntrypointLookup;
+use Symfony\WebpackEncoreBundle\Asset\EntrypointLookupCollection;
+
+class ExceptionListener
+{
+    private $entrypointLookupCollection;
+
+    private $entrypointNames;
```
Comment (weaverryan) [inline src/EventListener/ExceptionListener.php]: I believe these are `buildNames` - we should change `entrypoint` -> `build` everywhere in this class

File: src/EventListener/ExceptionListener.php [hunk 2]
```diff
@@ -0,0 +1,26 @@
+<?php
+
+namespace Symfony\WebpackEncoreBundle\EventListener;
```
Comment (weaverryan) [inline src/EventListener/ExceptionListener.php:10]: can you add LICENSE header at the top?

File: src/EventListener/ExceptionListener.php [hunk 3]
```diff
@@ -0,0 +1,26 @@
...
+        $this->entrypointNames = $entrypointNames;
+    }
+
+    public function onKernelException()
+    {
+        foreach ($this->entrypointNames as $entrypointName) {
+            $this->entrypointLookupCollection->getEntrypointLookup($entrypointName)->reset();
+        }
+    }
+}
```
Comment (weaverryan) [inline src/EventListener/ExceptionListener.php:32]: Could we add a very basic unit test for this class? There isn't much to test, but having at least ONE basic test will protect us from making any super silly typos now or in the future.

File: src/Resources/config/services.xml [hunk 4]
```diff
@@ -50,6 +50,12 @@
             <tag name="cache.pool" />
         </service>
 
+        <service id="webpack_encore.exception_listener" class="Symfony\WebpackEncoreBundle\EventListener\ExceptionListener">
+            <tag name="kernel.event_listener" event="kernel.exception" />
+            <argument type="service" id="webpack_encore.entrypoint_lookup_collection" />
+            <argument /> <!-- build list of entrypoint paths -->
```
Comment (weaverryan) [inline src/Resources/config/services.xml]:
```suggestion
            <argument /> <!--collection of build names -->
```

**Review by weaverryan — CHANGES_REQUESTED** [review]
Minor comments - thanks for moving this forward!

**Comment by tbmatuka** [comment]
@weaverryan should be all done, can you take a look?

**Comment by tbmatuka** [comment]
@weaverryan can you please take a look?

**Comment by tbmatuka** [comment]
@weaverryan it's been a month now, can you please take a quick look so that we can move this along?

**Comment by tbmatuka** [comment]
@weaverryan @Lyrkan this has been waiting for review/merge almost three months now, can we please move it along?

**Comment by weaverryan** [comment]
Sorry for the long delay @tbmatuka - but thank you SO much for finishing this :). Cheers!
