### PR TITLE
[stimulus-controller] fix bool attributes from being rendered incorrectly

### LINKED ISSUE #118: stimulus_controller() improperly adds a value attribute when set to false
Hi!

Suppose you have this controller:

```js
// assets/controllers/testing_controller.js
import { Controller } from 'stimulus';

export default class extends Controller {
    static values = {
        isEnabled: Boolean
    }

    connect() {
        console.log(this.isEnabledValue);
    }
}
```

Then you enable this in a template:

```twig
<div
    {{ stimulus_controller('testing', {
        isEnabled: false
    }) }}
></div>
```

The expected behavior is that, on load, the log would say `false`. But, instead, you will get true. The cause is that the HTML is rendering like this:

```html
<div data-controller="testing" data-testing-is-enabled-value></div>
```

Notice the presence of the attribute (though it's not set to a value). It appears that, for boolean values, (we should triple check this) the presence of the attribute is enough to make it be set to `true`.

The fix would be to:

When a value is specifically set to `false`, we would render NO attribute. If it's set to any other value - even `null` - I think we DO need to set the attribute... because we don't know if the value is a Boolean type from PHP... or maybe a string. Though, I'm not sure if this really matters. But not setting the attribute for `null` or `''` seems... like we might be being too hands on, and the only issue I'm aware of currently is with the boolean.

Cheers!

### PR DESCRIPTION
**Pull request by jrushlow**
fixes #118

### CODE REVIEW

**Comment by jrushlow** [comment]
related tests pass - failures related to deprecation that is fixed in #122

File: tests/IntegrationTest.php [hunk 1]
```diff
@@ -261,6 +261,12 @@ public function provideRenderStimulusController()
             'controllerValues' => ['myValue' => 'scalar-value'],
             'expected' => 'data-controller="my-controller" data-my-controller-my-value-value="scalar-value"',
         ];
+
+        yield 'false-attribute-value-is-not-rendered' => [
+            'dataOrControllerName' => 'false-controller',
+            'controllerValues' => ['isEnabled' => false],
+            'expected' => 'data-controller="false-controller"',
+        ];
```
Comment (weaverryan) [inline tests/IntegrationTest.php:275]: I did some more digging into this... and I think my proposed solution (which you implemented perfectly) is not... perfect ;).

For this test case:

```html
<!-- current output -->
<div
    data-controller="false-controller"
    data-false-controller-is-enabled-value=""
>
```

The `=""` for a `false` value is the problem. It should be `="false"`, which I've determined DOES cause the value in the controller to be `false`. Similarly, for `true`, the attribute should be `="true"`. Additionally, omitting the attribute entirely would cause `this.hasIsEnabledValue` (you can use a "hasser" like this to check for the existence of a value) to incorrectly return false with this current PR.

So I think the fix is to "fix" how we convert boolean values:

```
<!-- if isEnabled is passed as FALSE -->
<div
    data-controller="false-controller"
    data-false-controller-is-enabled-value="false"
>

<!-- if isEnabled is passed as TRUE -->
<div
    data-controller="false-controller"
    data-false-controller-is-enabled-value="true"
>
```

Comment (jrushlow) [reply tests/IntegrationTest.php:275]: that make sense.. done. keeping this "unresolved" for future reference.

File: tests/IntegrationTest.php [hunk 2]
```diff
@@ -214,7 +214,7 @@ public function provideRenderStimulusController()
                 ],
             ],
             'controllerValues' => [],
-            'expected' => 'data-controller="my-controller" data-my-controller-boolean-value="1" data-my-controller-number-value="4" data-my-controller-string-value="str"',
+            'expected' => 'data-controller="my-controller" data-my-controller-boolean-value="true" data-my-controller-number-value="4" data-my-controller-string-value="str"',
```
Comment (jrushlow) [inline tests/IntegrationTest.php:217]: i've implemented `(string) true|false` for the rendered value. But this "breaks" the previous `1` === `true` output even though false was blank. 

I personally prefer `true|false` over `1|0` as it's clear that the value is not intended to be an `int` / `(string)` number. But would this be considered BC even though the PR is intended to fix `false` bool's?

Comment (hvt) [reply tests/IntegrationTest.php:217]: Do not think this is a BC break, because one who defined a Stimulus value as `Boolean`, and the value was true-thy, having it previously rendered as `..-value="1"`, which in Stimulus was correctly interpreted as `true`.

And fixing that the `false` value was not being rendered as `..-value="false"` means imo it's currently incorrect, and of course the exact purpose of your PR ;].

**Comment by hvt** [comment]
Just hit this in my project, and wanted to let you know this PR fixed it for me :].

**Comment by jrushlow** [comment]
> Just hit this in my project, and wanted to let you know this PR fixed it for me :].

Awesome! That's good to hear - we should be able to get this pushed out pretty quickly.

**Comment by weaverryan** [comment]
Thanks for the nice fix Jesse - and to @hvt also for double-checking it for us in a real app <3
